"""Gabarito de avaliacao da busca: pergunta -> documentos que deveriam responder.

ESTE E UM GABARITO DE EXEMPLO. As perguntas abaixo apontam para os livros de
UMA base especifica -- a que gerou os numeros do README. Se os seus livros forem
outros, os alvos nao existem e o avaliador vai medir zero.

Para medir a SUA base: troque `PERGUNTAS` por perguntas suas, cada uma com os
pedacos do nome da pasta do documento que deveria responder. Depois rode
`avaliar_dominio.py`. E para isso que o avaliador vem junto.

---

THIS IS AN EXAMPLE GROUND TRUTH. The questions below point at the books of ONE
specific library -- the one that produced the README numbers. With a different
shelf the targets do not exist and the evaluator will score zero.

To measure YOUR library: replace `PERGUNTAS` with your own questions, each with
the fragments of the target document folder name. Then run `avaliar_dominio.py`.

Regras que mantem o gabarito honesto:

- a pergunta e escrita como o dono da base perguntaria, em linguagem natural,
  sem usar o vocabulario exato do livro (senao vira teste de casamento de string);
- o alvo e documento que trata do tema **centralmente**, nao de passagem;
- documento que a curadoria ja marcou como ruim (PDF errado, traducao
  automatica de baixa qualidade) nunca e alvo;
- a versao em ingles existe para o BM25 bilingue competir em pe de igualdade —
  e o que um agente faria antes de consultar.

Cada entrada: (pergunta_pt, pergunta_en, [pedacos do nome da pasta alvo]).
"""

PERGUNTAS = [
    # ---------------------------------------------------------------- vendas
    ("como responder quando o cliente diz que esta muito caro",
     "how to answer when the customer says it is too expensive",
     ["gap-selling", "pricing-creativity"]),
    ("que perguntas fazer numa visita para o cliente perceber o problema sozinho",
     "questions that make the buyer realize the problem themselves in a sales call",
     ["spin-selling", "gap-selling"]),
    ("como manter o funil cheio fazendo contato novo todo dia",
     "keeping the pipeline full with daily new prospecting",
     ["fanatical-prospecting"]),
    ("vale separar quem procura cliente de quem fecha a venda",
     "should we split the role of finding leads from closing deals",
     ["predictable-revenue"]),
    ("o que a pesquisa mostra sobre meta e comissao de vendedor",
     "what research shows about sales quota and commission",
     ["incrivel-ciencia"]),
    ("como descobrir a diferenca entre a situacao atual e a desejada do cliente",
     "finding the gap between the customer current state and desired state",
     ["gap-selling"]),

    # ------------------------------------------------------- copy e persuasao
    ("que tipos de abertura existem para uma carta de vendas",
     "types of lead openings for a sales letter",
     ["great-leads"]),
    ("como escrever um titulo que faz a pessoa continuar lendo",
     "how to write a headline that makes the reader keep going",
     ["copywriter-s-handbook", "copywriting-secrets", "great-leads"]),
    ("por que devolver um favor nos deixa mais propensos a dizer sim",
     "why reciprocity makes people more likely to agree",
     ["influence-manipulation"]),
    ("como montar a narrativa com o cliente no papel de heroi",
     "framing the story with the customer as the hero",
     ["building-a-story-brand"]),
    ("qual a estrutura de um texto de venda do inicio ao pedido",
     "structure of a sales copy from opening to the call to action",
     ["copywriting-secrets", "quickstart-copywriting", "copywriter-s-handbook"]),

    # ------------------------------------------- posicionamento e precificacao
    ("como definir para quem meu produto serve e contra o que ele compete",
     "how to define who the product is for and what it competes against",
     ["obviously-awesome"]),
    ("como cobrar pelo valor entregue em vez de por hora trabalhada",
     "charging for value delivered instead of hourly billing",
     ["pricing-creativity"]),
    ("por que oferecer tres opcoes de preco em vez de uma",
     "why offer three pricing options instead of one",
     ["pricing-creativity"]),
    ("como transformar servico avulso em receita que se repete todo mes",
     "turning one-off service into recurring monthly revenue",
     ["automatic-customer"]),
    ("como escolher um nicho estreito e virar referencia nele",
     "choosing a narrow niche and becoming the expert in it",
     ["business-of-expertise"]),
    ("por que marca cara nao faz promocao nem desconto",
     "why luxury brands never discount",
     ["luxury-strategy"]),
    ("como conversar com cliente sem receber elogio vazio sobre a ideia",
     "talking to customers without getting polite useless praise",
     ["mom-test"]),
    ("como decidir o que planejar antes de comecar um projeto",
     "deciding how much to plan before committing to a project",
     ["inteligencia-pragmatica"]),

    # ------------------------------------------------------- ux e conversao
    ("como usar espacamento e contraste para guiar o olho na tela",
     "using spacing and contrast to guide the eye on screen",
     ["refactoring-ui", "leis-da-psicologia"]),
    ("por que o visitante nao deveria precisar pensar para navegar",
     "why the visitor should not have to think to navigate",
     ["dont-make-me-think"]),
    ("como testar mudancas na pagina para vender mais",
     "testing page changes to increase conversion",
     ["making-websites-win"]),
    ("como manter conversa com usuario toda semana sem virar projeto",
     "keeping weekly customer interviews as a habit",
     ["continuous-discovery"]),
    ("como usar progresso e recompensa para manter a pessoa engajada",
     "using progress and reward to keep people engaged",
     ["actionable-gamification"]),
    ("quanto tempo a pessoa espera antes de desistir de uma tela",
     "how long users wait before abandoning a slow screen",
     ["leis-da-psicologia", "making-websites-win"]),

    # ---------------------------------------------------- engenharia de software
    ("como limitar a complexidade de um metodo para caber na cabeca",
     "limiting method complexity so it fits in your head",
     ["code-that-fits"]),
    ("por que ciclo de retorno curto melhora o software",
     "why short feedback cycles improve software",
     ["modern-software", "code-that-fits"]),
    ("por que nao repetir o mesmo conhecimento em dois lugares do codigo",
     "why not repeat the same knowledge in two places in the code",
     ["pragmatic-programmer"]),
    ("como isolar o banco de dados do resto da aplicacao",
     "isolating the database from the rest of the application",
     ["architecture-patterns"]),
    ("quando escrever o teste antes do codigo compensa",
     "when writing the test before the code pays off",
     ["modern-software", "code-that-fits"]),

    # ------------------------------------------------------ python e dados
    ("como raspar dados de um site e tratar o html",
     "scraping data from a website and parsing the html",
     ["web-scraping"]),
    ("como funcionam compreensao de lista e gerador",
     "how list comprehensions and generators work",
     ["fluent-python", "pense-em-python"]),
    ("como prever uma serie com sazonalidade usando suavizacao",
     "forecasting a seasonal series with exponential smoothing",
     ["forecasting", "forecast-time-series"]),
    ("como equilibrar testar opcao nova e explorar a que ja funciona",
     "balancing exploration and exploitation when testing options",
     ["bandit-algorithms"]),
    ("quando um problema de negocio vale ser resolvido com aprendizado de maquina",
     "when a business problem is worth solving with machine learning",
     ["data-science-for-business"]),
    ("como treinar uma rede neural para classificar imagens",
     "training a neural network to classify images",
     ["aprendizado-profundo"]),

    # ----------------------------------------------------------- ia e llm
    ("quando usar RAG em vez de ajustar o modelo",
     "when to use RAG instead of fine-tuning the model",
     ["building-llms", "ai-engineering"]),
    ("como medir se a resposta do modelo esta boa",
     "how to evaluate whether a model output is good",
     ["ai-engineering", "building-llms"]),
    ("como montar um bot de atendimento sem programar do zero",
     "building a customer service bot without coding from scratch",
     ["snatchbot"]),
    ("o que e mecanismo de atencao num modelo de linguagem",
     "what is the attention mechanism in a language model",
     ["large-language-models-llm", "building-llms"]),

    # -------------------------------------------------- rust, frontend, algoritmo
    ("como a linguagem controla quem e dono da memoria",
     "how the language controls memory ownership and borrowing",
     ["rust-a-linguagem", "zero-to-production"]),
    ("como guardar estado e reagir a mudanca num componente",
     "holding state and reacting to change in a component",
     ["road-to-react"]),
    ("qual a diferenca de custo entre os algoritmos de ordenacao",
     "cost difference between sorting algorithms",
     ["javascript-algorithms"]),

    # ------------------------------------------------------------- marketing
    ("quais sao as leis do marketing de conteudo",
     "the laws of content marketing",
     ["tudo-e-conteu"]),
    ("o que acontece no cerebro na hora de decidir a compra",
     "what happens in the brain at the moment of buying",
     ["neurovendas", "rapido-e-devagar"]),

    # ------------------------------------------------------ treino e nutricao
    ("como treinar por zona de potencia e achar o limiar",
     "training with power zones and finding functional threshold",
     ["power-meter"]),
    ("como dividir a temporada em fases de treino",
     "periodizing the season into training phases",
     ["cyclist"]),
    ("o que comer para aguentar treino longo",
     "what to eat to sustain long endurance training",
     ["endurance-diet"]),

    # --------------------------------------------------- cognicao e decisao
    ("qual a diferenca entre pensar rapido por intuicao e devagar com esforco",
     "difference between fast intuitive thinking and slow effortful thinking",
     ["rapido-e-devagar"]),
    ("como um numero jogado no inicio influencia a estimativa depois",
     "how an initial number anchors a later estimate",
     ["rapido-e-devagar"]),
    ("qual a relacao entre tamanho do grupo social e o cerebro",
     "relation between social group size and the brain",
     ["research-and-perspectives"]),

    # ------------------------------------------------------------ design e arte
    ("como gerar forma visual a partir de regra e algoritmo",
     "generating visual form from rules and algorithms",
     ["generative-algorithms"]),
    ("o que distingue arte de artesanato ou entretenimento",
     "what distinguishes art from craft or entertainment",
     ["principles-of-art"]),

    # ================================================================
    # Leva de 10/09/2026 — cobre os documentos que entraram depois do
    # gabarito original. Sem elas a avaliacao so media regressao: 123
    # dos 178 documentos nao eram alvo de pergunta nenhuma, e cada leva
    # nova aparecia como queda porque so acrescentava distrator.
    # ================================================================

    # ------------------------------------------- agentes, harness, skills
    ("o que os desenvolvedores costumam escrever no arquivo de regras do assistente de codigo",
     "what developers actually write in coding assistant rule files",
     ["cursorrules"]),
    ("como montar o ambiente em que o agente age e observa o resultado",
     "designing the environment where an agent acts and observes",
     ["agentic-environment-engineering"]),
    ("que dado pessoal vaza quando o agente tem acesso as minhas ferramentas",
     "what personal data leaks when an agent has tool access",
     ["agents-that-know-too-much"]),
    ("agente que fica ligado o tempo todo guarda o que, e quem controla isso",
     "persistent state and governance in always-on agents",
     ["always-onagents"]),
    ("a memoria do agente deveria ser um sistema proprio em vez de um banco de vetor",
     "should agent memory be a native system instead of a vector store",
     ["are-we-ready-for-an-agent-native"]),
    ("quanto custa de verdade rodar agente que escreve codigo, contando a conferencia",
     "true cost and verification burden of agentic software development",
     ["beyond-code-generation"]),
    ("como usar o Claude Code no dia a dia, comandos e configuracao",
     "practical handbook for using Claude Code day to day",
     ["claude-code-complete-user-handbook"]),
    ("vale o agente escrever codigo para chamar a ferramenta em vez de chamar direto",
     "using generated code as the harness for agent tool calls",
     ["code-as-agent-harness"]),
    ("como administrar o contexto por programa numa tarefa que dura muito",
     "programmatic context management for long-horizon agents",
     ["context-as-an-environment"]),
    ("como escolher o que entra no contexto pensando na decisao que o agente vai tomar",
     "counterfactual context selection and compression for tool agents",
     ["decision-aware-memory-cards"]),
    ("instrucao feita para um desenvolvedor especifico rende mais que instrucao generica",
     "do developer-specific skills beat generic ones for coding agents",
     ["do-personalized-skills"]),
    ("como uma biblioteca de habilidades de agente cresce e envelhece com o tempo",
     "lifecycle and taxonomy of evolving agent skill libraries",
     ["dynamic-agent-skills"]),
    ("como avaliar agente de codigo sem rodar o benchmark inteiro toda vez",
     "cheaper coding agent evaluation using execution trajectories",
     ["efficient-swe-agent-benchmarking"]),
    ("como escrever documentacao que o agente de codigo consiga usar",
     "writing documentation that coding agents can actually consume",
     ["from-agent-behaviour-to-agent-friendly"]),
    ("panorama de como se projeta o sistema em volta do modelo para ele executar tarefa",
     "survey of agent system and harness design for task completion",
     ["from-question-answering-to-task-completion"]),
    ("como fazer o agente repetir o mesmo caminho toda vez que roda",
     "making an agent reproduce the same execution path every run",
     ["harness-engineering-for-predictable"]),
    ("que padroes de arquitetura aparecem no codigo-fonte dos agentes de programacao",
     "source-code taxonomy of coding agent architectures",
     ["inside-the-scaffold"]),
    ("cortar o historico melhora ou piora o agente numa tarefa comprida com ferramenta",
     "does trimming history help long-horizon tool-using agents",
     ["less-context-better-agents"]),
    ("que mecanismos de memoria existem para agente autonomo e como medir cada um",
     "mechanisms and evaluation of memory for autonomous agents",
     ["memory-for-autonomous-llm-agents"]),
    ("como um plugin de agente e mantido e o que quebra quando o programa hospedeiro muda",
     "maintenance and co-evolution of agent plugins",
     ["on-the-maintenance-and-co-evolution"]),
    ("os benchmarks de programacao medem o que o agente faz de verdade no trabalho",
     "coding benchmarks are misaligned with real agentic engineering",
     ["position-coding-benchmarks"]),
    ("de que jeitos um sistema de agente consegue melhorar a si mesmo",
     "ways an agentic system can improve itself",
     ["self-improvements-in-modern-agentic"]),
    ("como o agente decide por onde comecar a ler um repositorio que ele nao conhece",
     "how coding agents explore an unfamiliar repository",
     ["swe-explore"]),
    ("como avaliar agente de codigo numa sessao com a pessoa interrompendo e corrigindo",
     "evaluating coding agents in interactive user sessions",
     ["swe-together"]),
    ("panorama de agente que trabalha dentro da linha de comando",
     "survey of AI agents working in command-line environments",
     ["terminal-agents"]),
    ("os varios programas que rodam agente estao convergindo para a mesma arquitetura",
     "architectural convergence across LLM agent harnesses",
     ["the-empire-long-divided"]),
    ("como aproveitar cache de prompt para baratear o agente",
     "cache-efficient context management to cut agent cost",
     ["tokenpilot"]),
    ("quanto custa servir um sistema de memoria de agente em producao",
     "serving cost of agentic memory systems",
     ["total-recall-at-what-cost"]),
    ("que superficie de ataque abre quando o agente usa MCP e habilidades de terceiro",
     "attack surface of MCP, skills and tool calling",
     ["when-agents-act-on-web3"]),

    # ------------------------------------------------ seguranca de LLM e agente
    ("as defesas contra injecao de prompt aguentam contexto longo",
     "do prompt injection defenses hold up in long context",
     ["longpibench"]),
    ("o que quebra quando varios agentes seguros trabalham juntos",
     "security failures that emerge in multi-agent LLM systems",
     ["sok-when-safe-agents-fail-together"]),
    ("da para extrair o raciocinio interno de um modelo fechado pela API",
     "extracting hidden reasoning traces from proprietary model APIs",
     ["stealing-reasoning-traces"]),
    ("por que defesa que so olha a superficie do texto nao segura vazamento de dado",
     "why surface-level defenses fail against indirect prompt-injection exfiltration",
     ["the-framing-gap"]),
    ("como um servidor de ferramenta ganha confianca primeiro e vira hostil depois",
     "staged trust attacks on MCP servers",
     ["trustshiftprobe"]),

    # ------------------------------------------------------------- LLM e modelo
    ("quando a busca por palavra ainda ganha do embedding num RAG grande",
     "when lexical retrieval still beats dense retrieval at scale in RAG",
     ["bm25-wins-at-scale"]),
    ("em que etapa da vida do modelo nasce a alucinacao e o que reduz",
     "lifecycle causes and mitigations of hallucination in LLMs",
     ["hallucinations-in-llms"]),
    ("por que uma instrucao empacotada funciona ate certo ponto e depois para de funcionar",
     "why agent skills work until they stop working",
     ["demystifying-agent-skills"]),
    ("colocar a configuracao da IA em markdown versionado no repositorio muda alguma coisa",
     "committing markdown AI configuration into the repository",
     ["a-few-pages-of-markdown"]),
    ("a memoria deveria reconstruir a lembranca em vez de so devolver o trecho guardado",
     "graph memory that reconstructs instead of retrieving",
     ["memory-is-reconstructed"]),
    ("que familias de tecnica de raciocinio existem e como se relacionam",
     "structured survey of reasoning methods in language models",
     ["the-periodic-table-of-llm-reasoning"]),
    ("como decidir para qual modelo mandar cada pedido",
     "infrastructure for routing each request to the right model",
     ["llmrouter"]),
    ("da para melhorar o modelo depois do treino sem dado rotulado",
     "unsupervised post-training of foundation models",
     ["unsupervised-post-training"]),
    ("o que acontece com o agente de codigo quando uma dependencia quebra em silencio",
     "can coding agents survive hidden breakage in dependencies",
     ["update-from-hell"]),
    ("vale montar grafo em varias etapas para responder pergunta de dominio",
     "multi-step graph RAG with a compact domain adapter",
     ["ragu-a-multi-step-graphrag"]),

    # ------------------------------------------------- engenharia de software
    ("como tratar seguranca como propriedade do sistema inteiro e nao de uma peca",
     "systems thinking applied to safety engineering",
     ["engineering-a-safer-world"]),
    ("como fazer software em que o dado e do usuario e funciona sem nuvem",
     "local-first software where the user owns the data",
     ["local-first-software"]),
    ("como saber se meus testes prestam mudando o codigo de proposito",
     "mutation testing to measure how good a test suite is",
     ["mutation-testing"]),
    ("como descobrir API que falha calada, sem devolver erro",
     "measuring silent failure in production APIs",
     ["silentprobe"]),
    ("o agente aguenta uma cadeia longa de chamadas de API que dependem uma da outra",
     "benchmarking agents on long chains of dependent API calls",
     ["apiflow-bench"]),

    # -------------------------------------------------------------- vendas
    ("como fazer o outro lado reconhecer que eu entendi a posicao dele numa negociacao",
     "getting the other side to admit you understood their position",
     ["never-split-the-difference"]),
    ("que perfil de vendedor rende mais em venda complexa",
     "which salesperson profile performs best in complex sales",
     ["challenger-sale"]),
    ("como organizar o acompanhamento de quem ainda nao respondeu",
     "building a system for following up with unresponsive prospects",
     ["sell-it-like-serhant"]),
    ("vale usar roteiro pronto na ligacao de venda",
     "should you use prepared scripts on a sales call",
     ["sales-scripts-that-sell"]),

    # ------------------------------------------ posicionamento e modelo de negocio
    ("como montar uma oferta dificil de recusar sem baixar o preco",
     "building an offer so good people feel stupid saying no",
     ["100m-offers"]),
    ("por que solucao que nao faz sentido logico as vezes funciona melhor",
     "why psychologically illogical solutions often work better",
     ["alchemy"]),
    ("por que o fundador deveria se prender ao problema e nao a solucao",
     "falling in love with the problem instead of the solution",
     ["apaixone-se-pelo-problema"]),
    ("o que a pesquisa diz sobre construir marca pessoal",
     "what research says about building a personal brand",
     ["the-one-thing-personal-brand"]),

    # ------------------------------------------------------ copy e persuasao
    ("o que fazer quando todo mundo no mercado ja ouviu a mesma promessa",
     "writing copy for a market that already heard every claim",
     ["breakthrough-advertising"]),

    # ------------------------------------------------------------ marketing
    ("como escolher por qual canal de aquisicao comecar",
     "choosing which acquisition channel to try first",
     ["traction"]),
    ("como estruturar conteudo e anuncio no Instagram para um negocio",
     "structuring Instagram content and ads for a business",
     ["instagram-marketing"]),

    # ------------------------------------------------ financas e investimentos
    ("como avaliar se uma acao esta barata olhando o balanco da empresa",
     "valuing a stock from its financial statements",
     ["security-analysis"]),
    ("o que e margem de seguranca e por que exigir uma",
     "what a margin of safety is and why to demand one",
     ["margin-of-safety"]),
    ("que criterios Buffett e Munger usam para escolher em que empresa por dinheiro",
     "the criteria Buffett and Munger use to pick a company",
     ["o-jeito-de-warren-buffett", "a-sabedoria-de-charlie-munger"]),
    ("como funciona Tesouro Direto e renda fixa no Brasil",
     "how Brazilian treasury bonds and fixed income work",
     ["poupando-e-investindo"]),
    ("o que causou o colapso financeiro de 2008",
     "what caused the 2008 financial collapse",
     ["a-jogada-do-seculo"]),
    ("como aproveitar os ciclos da bolsa em investimento de longo prazo",
     "profiting from market cycles over the long run",
     ["lucrando-com-acoes"]),

    # ------------------------------------------------------ busca e recuperacao
    ("como usar o sinal de quem clicou para melhorar o ranking",
     "using click signals from users to improve ranking",
     ["ai-powered-search"]),
    ("como funciona indice invertido e por que ele e rapido",
     "how an inverted index works and why it is fast",
     ["introduction-to-information-retrieval"]),
    ("como envenenar a base de um sistema de recuperacao e como defender",
     "poisoning attacks and defenses in retrieval-augmented systems",
     ["retrieved-but-not-reliable"]),

    # ------------------------------------------------- cognicao e comportamento
    ("como um produto cria habito na pessoa que usa",
     "how a product builds a habit in its user",
     ["hooked"]),
    ("que diferenca faz acreditar que a habilidade pode ser desenvolvida",
     "what changes when you believe ability can be developed",
     ["mindset"]),
    ("o que o excesso de prazer facil faz com o cerebro",
     "what constant easy pleasure does to the brain",
     ["nacao-dopamina"]),
    ("quais sao os pressupostos e os niveis logicos da PNL",
     "the presuppositions and logical levels of NLP",
     ["formacao-master-em-pnl"]),

    # ------------------------------------------------------------ UX e conversao
    ("como organizar um formulario para a pessoa nao desistir no meio",
     "organizing a form so people finish filling it",
     ["web-form-design"]),
    ("como rodar teste A/B sem chegar a conclusao errada",
     "running online controlled experiments without wrong conclusions",
     ["trustworthy-online-controlled-experiments"]),
    ("como manter padrao visual entre paginas com componente reaproveitavel",
     "keeping visual consistency with reusable components",
     ["design-systems", "modular-web-design"]),
    ("principios classicos de design com nome proprio, tipo regra 80/20 e affordance",
     "classic named design principles like the 80/20 rule and affordance",
     ["universalprinciplesofdesign", "the-pocket-universal-principles"]),
    ("como escolher e compor tipografia para texto longo",
     "choosing and setting type for long-form text",
     ["thinking-with-type", "elementos-do-estilo-tipografico"]),
    ("como medir a experiencia de usar um assistente de IA",
     "benchmarking the user experience of AI assistants",
     ["uxbench"]),
    ("chatbot de proposito geral aumenta engajamento de verdade",
     "do general-purpose chatbots actually increase engagement",
     ["chatbots-fomentam-engajame"]),
    ("interface gerada por IA cria padrao escuro sozinha",
     "emergent dark patterns in AI-generated user interfaces",
     ["emergent-dark-patterns"]),

    # ------------------------------------------------------------ design e arte
    ("como combinar cor usando contraste e circulo cromatico",
     "combining colors using contrast and the color wheel",
     ["johannes-itten"]),
    ("que regras um designer classico impoe a si mesmo",
     "the rules a classic designer imposes on himself",
     ["vignelli-canon"]),

    # ------------------------------------------------------ seguranca ofensiva
    ("como se faz teste de invasao e exploracao de vulnerabilidade",
     "penetration testing and vulnerability exploitation",
     ["gray-hat-hacking"]),
    ("como usar Python para escrever ferramenta de seguranca ofensiva",
     "using Python to write offensive security tooling",
     ["gray-hat-python", "hacking-with-python"]),

    # ------------------------------------------------------------ frontend
    ("como fazer componente acessivel para quem usa leitor de tela",
     "accessible component patterns for screen reader users",
     ["inclusive-design-patterns"]),

    # ------------------------------------------------------------ python
    ("como comecar a analisar dado com Python do zero",
     "getting started analyzing data with Python from scratch",
     ["python-para-todos", "python-programming-for-beginners"]),
]

# formato usado pelo avaliador: (pt, alvos) e o de-para pt -> en
GABARITO = [(pt, alvos) for pt, _en, alvos in PERGUNTAS]
TRADUCAO = {pt: en for pt, en, _a in PERGUNTAS}
